[package]
name = "hs"
version = "0.1.0"
edition = "2018"

[dependencies]
chrono = "0.4.19"
unindent = "0.1.7"
docopt = "1.1.1"
# Used by docopt.
serde = { version = "1.0.126", features = ["derive"] }
